export const CHECK_NETWORK = 'check_network';
export const FETCH_DATA = 'fetch_data';
export const EPISODES_FETCHED = 'episodes_fetched';
export const SEARCH_CHANGED = 'search_changed';
export const SEARCH_RESULTS = 'search_results';
export const SELECTED_EPISODE = 'selected_episode';
export const FADE_NAVBAR = "fade_navbar";
export const NEW_CONTENT_SEARCH = "new_content_search";
export const NEW_CONTENT_DATA = "new_content_data"
export const NEW_CONETNT_ADDED = "add_new_conetnt"
export const CLEAR_NEW_CONTENT_VALUES = "clear_new_content_values"
export const CHANGE_RESPONSE_COLOR = "change_response_color"
export const EPISODE_TAG_REPORTED = "episode_tag_reported"
export const EPISODE_TAG_COMMENDED = "episode_tag_commended"
export const EPISODE_TAG_ADDED = "episode_tag_added"
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const USER_LOGED_IN = 'USER_LOGED_IN';
export const SET_USER = 'SET_USER';
// export const GET_MOVIE_MEDIA_SIZE = "get_movie_media_size";
// export const ARTIST_CHANGED = 'artist_changed';
// export const ARTIST_SELECTED = 'artist_selected';
// export const ARTIST_SEARCHED = 'artist_searched';
// export const SONGLIST_GETSONGS = 'songlist_getsongs'