export const CHECK_NETWORK = 'check_network';
export const FETCH_DATA = 'fetch_data';
export const EPISODES_FETCHED = 'episodes_fetched';
export const SEARCH_CHANGED = 'search_changed';
export const SEARCH_RESULTS = 'search_results';
export const SELECTED_EPISODE = 'selected_episode';
export const FADE_NAVBAR = "fade_navbar";
// export const SHOW_FULL_SYNOPSIS = "show_full_synopsis";
// export const RESET_MOVIE_DETAIL_STATE = 'reset_movie_detail_state';
// export const GET_MOVIE_MEDIA_SIZE = "get_movie_media_size";
// export const ARTIST_CHANGED = 'artist_changed';
// export const ARTIST_SELECTED = 'artist_selected';
// export const ARTIST_SEARCHED = 'artist_searched';
// export const SONGLIST_GETSONGS = 'songlist_getsongs'